[[testimony]]
quote="It is great that someone looks at privacy issues from a scientific point of view."
name="SURVEY PARTICIPANT, Government Sector, Germany"

[[testimony]]
quote="“It is important for us in the privacy community to understand how different voices and stakeholders influence the broader discourse on privacy, and this project helps us think about the diversity of research, advocacy, and regulatory agendas across our community”"
name=" MICHAEL ZIMMER, Privacy & Ethics Scholar,  Marquette University"


[[testimony]]
quote="“I’m really glad that you’re doing this work — this kind of insight is sorely needed in the privacy space and I’m looking forward to reading the results.”"
name="SURVEY PARTICIPANT, Private Sector (Tech), United States"

[[testimony]]
quote="“This is brilliant — looking forward to hear findings from this survey.”"
name="SURVEY PARTICIPANT, Academia, United States"

[[testimony]]
quote="“I appreciated that the survey wasn’t time consuming to fill out and that the questions were clear. I’d be really interested in understanding the reasons for / drivers of people’s perceptions and also in comparing responses across regions.”"
name= "SURVEY PARTICIPANT, Private Sector (Tech), United States"
