
[[card]]
image = ""
title = "Take the current wave 4 survey now!"
description="""By answering the 2-4 minute survey, you share your valuable insights and perspectives and contribute to our goal to understand and assess AI privacy perceptions, actions, and recommendations regarding privacy in the context of artificial intelligence (AI) systems.
"""
button_link="http://google.com"
button_text="Go to our survey"


[[card]]
image = ""
title = "Submit a question!"
description="""You want to tell us more about your AI privacy perceptions, actions and recommendations? 
"""



[[card]]
image = ""
title = "Use data for your own research/project!"
description="""You are keen to use previous results of the questionnaire to build up your research work or for your project at work. Soon you can download the anonymized raw data from GESIS - Leibniz Institute for the Social Sciences. If you need the data now, reach out to us. 
"""







