

[[card]]
image = ""
title = "Become a panel participant!"
description="""You would like to be part of the debate, part of TAPP and involved in the design of upcoming questions? We are forming an advisory board with stakeholders from academia, industry, public sector, NGOs and beyond to ensure diverse perspectives. Their insights will steer and align our research project's future path."""
button_link="mailto:info@privacyperceptions.org"
button_text="Send us an email"

[[card]]
image = ""
title = "Join the advisory board!"
description="""You would like to be part of the debate, part of TAPP and involved in the design of upcoming questions? We are forming an advisory board with stakeholders from academia, industry, public sector, NGOs and beyond to ensure diverse perspectives. Their insights will steer and align our research project's future path.
"""

[[card]]
image = ""
title = "Become an interview partner!"
description="""Inform through quantitative data"""


[[card]]
image = ""
title = "Feature blog post!"
description="""You are working in the area of AI privacy and would like to spread the word about work you or others did. Please share it with us and we are happy to feature it in our blog.
"""


